{% set name = "akismet" %}
{% set version = "1.2.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/akismet-{{ version }}.tar.gz
  sha256: f3790489ea091d43a14717f1f6b1a0a86af2ac235d10b13742ee0ea064ff8ea7

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - requests

test:
  imports:
    - akismet
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/ubernostrum/akismet
  summary: A Python interface to the Akismet spam-filtering API.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mxr-conda
    - Admax18
