{% set name = "akismet" %}
{% set version = "24.11.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/akismet-{{ version }}.tar.gz
  sha256: 1fefa05e6500a8b41c43bd1dbff8e04a6c76cc16d217981075d70673731244bd

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - python >=3.5
    - requests

test:
  imports:
    - akismet
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ubernostrum/akismet
  summary: A Python interface to the Akismet spam-filtering API.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mxr-conda
    - Admax18
